"""add missing columns

Revision ID: a5f8d72b67dc
Revises: 2bd654dc1b04
Create Date: 2026-06-01 11:19:11.210138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5f8d72b67dc'
down_revision: Union[str, None] = '2bd654dc1b04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('delivery_mode', sa.String(), nullable=True))
    op.add_column('clients', sa.Column('delivery_transport_companies', sa.JSON(), nullable=True))
    op.add_column('delivery_schedules', sa.Column('delivery_mode', sa.String(), nullable=True))
    op.add_column('delivery_schedules', sa.Column('transport_companies', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('delivery_schedules', 'transport_companies')
    op.drop_column('delivery_schedules', 'delivery_mode')
    op.drop_column('clients', 'delivery_transport_companies')
    op.drop_column('clients', 'delivery_mode')
    # ### end Alembic commands ###
